In [1]:
# SkLearn Imports
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier

# Data Analytics Imports
import numpy as np
import pandas as pd

# Data Visualisation Imports
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import plot, iplot, init_notebook_mode, download_plotlyjs

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Loading the Dataset

In [2]:
# Loading the dataset
iris = load_iris()
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
print("Features Used: ")
print(iris["feature_names"])

Features Used:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [4]:
print("Targets Used: ")
print(iris["target_names"])

Targets Used:
['setosa' 'versicolor' 'virginica']

In [5]:
print("Description of the Dataset (similar to pd.DataFrame.describe()): ")
print(iris["DESCR"])

Description of the Dataset (similar to pd.DataFrame.describe()):
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica

    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
    :Class Distribution: 33.3% for each of 3 classes.
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. topic:: References

   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
     Mathematical Statistics" (John Wiley, NY, 1950).
   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
     Structure and Classification Rule for Recognition in Partially Exposed
     Environments".  IEEE Transactions on Pattern Analysis and Machine
     Intelligence, Vol. PAMI-2, No. 1, 67-71.
   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
     on Information Theory, May 1972, 431-433.
   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
     conceptual clustering system finds 3 classes in the data.
   - Many, many more ...

## Converting Arrays into a Pandas DataFrame

In [6]:
df_iris = pd.DataFrame(iris["data"], columns=iris["feature_names"])
df_iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df_species = pd.DataFrame(iris["target"], columns=["species"])
df_species.head()

   species
0        0
1        0
2        0
3        0
4        0

In [8]:
df_iris_full = pd.concat([df_iris, df_species], axis=1)
df_iris_full.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
df_iris_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

## Creating a Training and Testing Set

In [10]:
# Making a 10 fold split of the dataset by default
split = StratifiedShuffleSplit(n_splits=1, test_size=0.10, random_state=17)
for train_idx, test_idx in split.split(df_iris_full, df_iris_full["species"]):
    strat_train = df_iris_full.iloc[train_idx]
    strat_test = df_iris_full.iloc[test_idx]

In [11]:
print(f"Shape of the Training Set: {strat_train.shape}")
strat_train.head()

Shape of the Training Set: (135, 5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
82,5.8,2.7,3.9,1.2,1
68,6.2,2.2,4.5,1.5,1
140,6.7,3.1,5.6,2.4,2
123,6.3,2.7,4.9,1.8,2
126,6.2,2.8,4.8,1.8,2

In [12]:
print(f"Shape of the Testing Set: {strat_test.shape}")
strat_test.head()

Shape of the Testing Set: (15, 5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
103,6.3,2.9,5.6,1.8,2
15,5.7,4.4,1.5,0.4,0
6,4.6,3.4,1.4,0.3,0
45,4.8,3.0,1.4,0.3,0
102,7.1,3.0,5.9,2.1,2

## Visualising and Gaining Insights

In [13]:
targets = iris["target_names"]

fig = px.scatter_3d(df_iris_full, x="petal length (cm)", y="petal width (cm)", z="sepal length (cm)", color="species",
                   hover_name=targets[df_iris_full["species"]],
                   labels={
                       "petal length (cm)": "Petal Length (cm)",
                       "petal width (cm)": "Petal Width (cm)",
                       "sepal length (cm)": "Sepal Length (cm)"
                   })
fig.update_traces(marker_line_width=4, marker_size=10)

**`Important`**  
From the above graph we can infer the following:
- `Virginica`: Highest Petal Length, Highest Sepal Length, Highest Sepal Width
- `Sentosa`: Lowest Petal Length, Lowest Sepal Length, Lowest Sepal Width

In [14]:
# Finding the correlation among the attributes
corr_matrix = df_iris_full.corr()
corr_matrix["species"].sort_values(ascending=False)

species              1.000000
petal width (cm)     0.956547
petal length (cm)    0.949035
sepal length (cm)    0.782561
sepal width (cm)    -0.426658
Name: species, dtype: float64

**`Inference`**  
- The results of the `Scatter Plot` are verified by the `Correlation Calculation`
- The `Petal Length` and `Petal Width` have very high `Positive Correlation` with the target attribute

## Visualising the Distribution of the Attributes

In [15]:
fig = px.scatter_matrix(df_iris_full.drop("species", axis=1))
fig.update_layout(font=dict(size=8))

## Building the Model

In [16]:
# Seperating the Training Set
X_train = strat_train.drop("species", axis=1)
y_train = strat_train["species"]

# Seperating the Test Set
X_test = strat_test.drop("species", axis=1)
y_test = strat_test["species"]

In [17]:
# Initialising the Model
tree_classifier = RandomForestClassifier()

# Training the Model
tree_classifier.fit(X_train, y_train)

RandomForestClassifier()

## Making Predictions

In [18]:
predictions = tree_classifier.predict(X_test)
n_correct = sum(predictions == y_test)
print("Score of Predictions: ", n_correct / len(predictions))

Score of Predictions:  1.0

<h2>
    This Completes by Notebook on the Iris Dataset<br>
    Kindly show appreciation if you found the notebook helpful<br>
</h2>
<h3>
    <b>I am also open to suggestion and constructive comments please share if any 🙂</b>
</h3>